package main

import ()

var Jewels = []Product{
	{Product_type_id:"jewels",Pid: "jewl-1", Poster: "bracelet_1.jpg", Name: "Royal Charm Bracelet", SKU: "SKU001", Price: 1200, Brand: "AuraGold", Category: "Jewelry", Color: "Gold", Material: "Gold", Weight: "10g", Size: "M", OriginalPrice: "1500", Sale: true, Discount: 20, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-2", Poster: "bracelet_2.jpg", Name: "Elegant Drape Bracelet", SKU: "SKU002", Price: 1100, Brand: "LuxeBand", Category: "Jewelry", Color: "Gold", Material: "Gold", Weight: "9g", Size: "S", OriginalPrice: "1400", Sale: true, Discount: 21, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-3", Poster: "chain_1.jpg", Name: "Stellar Silver Chain", SKU: "SKU003", Price: 2500, Brand: "NovaShine", Category: "Jewelry", Color: "Silver", Material: "Silver", Weight: "15g", Size: "L", OriginalPrice: "2800", Sale: true, Discount: 10, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-4", Poster: "chain_2.jpg", Name: "Regal Gold Chain", SKU: "SKU004", Price: 2600, Brand: "CrownLinks", Category: "Jewelry", Color: "Gold", Material: "Gold", Weight: "16g", Size: "L", OriginalPrice: "3000", Sale: true, Discount: 13, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-5", Poster: "chain_3.jpg", Name: "Twilight Shine Chain", SKU: "SKU005", Price: 2450, Brand: "Ornamo", Category: "Jewelry", Color: "Gold", Material: "Gold", Weight: "14g", Size: "M", OriginalPrice: "2700", Sale: true, Discount: 9, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-6", Poster: "chain_4.jpg", Name: "Lunar Grace Chain", SKU: "SKU006", Price: 2300, Brand: "ZephyrJewels", Category: "Jewelry", Color: "Silver", Material: "Silver", Weight: "13g", Size: "M", OriginalPrice: "2500", Sale: true, Discount: 8, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-7", Poster: "ring_1.jpg", Name: "Celestial Halo Ring", SKU: "SKU007", Price: 900, Brand: "InfinityOrnaments", Category: "Jewelry", Color: "Gold", Material: "Gold", Weight: "5g", Size: "S", OriginalPrice: "1000", Sale: true, Discount: 10, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-8", Poster: "ring_2.jpg", Name: "Dusk Whisper Ring", SKU: "SKU008", Price: 850, Brand: "Lumineux", Category: "Jewelry", Color: "Silver", Material: "Silver", Weight: "4.5g", Size: "M", OriginalPrice: "950", Sale: true, Discount: 11, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-9", Poster: "ring_3.jpg", Name: "Blush Bloom Ring", SKU: "SKU009", Price: 950, Brand: "RoséAllure", Category: "Jewelry", Color: "Rose Gold", Material: "Gold", Weight: "5.5g", Size: "S", OriginalPrice: "1050", Sale: true, Discount: 9, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-10", Poster: "jumkha_1.jpg", Name: "Golden Twilight Jhumka", SKU: "SKU010", Price: 1800, Brand: "Tradiva", Category: "Jewelry", Color: "Gold", Material: "Gold", Weight: "12g", Size: "M", OriginalPrice: "2000", Sale: true, Discount: 10, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-11", Poster: "jumkha_2.jpg", Name: "Silver Dewdrop Jhumka", SKU: "SKU011", Price: 1750, Brand: "EthnoGleam", Category: "Jewelry", Color: "Silver", Material: "Silver", Weight: "11g", Size: "M", OriginalPrice: "1900", Sale: true, Discount: 8, Ordered: false, AddToCart: false},
	{Product_type_id:"jewels",Pid: "jewel-12", Poster: "jumkha_3.jpg", Name: "Rose Dawn Jhumka", SKU: "SKU012", Price: 1850, Brand: "Kritika Jewels", Category: "Jewelry", Color: "Rose Gold", Material: "Gold", Weight: "11.5g", Size: "M", OriginalPrice: "2100", Sale: true, Discount: 12, Ordered: false, AddToCart: false},
}
