package main

import (
	"fmt"
	"glow/database"
	"glow/shared"
)

func insHomeCart() {
	category := []shared.Category{
		{Product_type_id: "cosmetics", Poster: "cosmetics.jpg", IsProduct: false},
		{Product_type_id: "jewels", Poster: "jewels.jpg", IsProduct: false},
		{Product_type_id: "mobile accessories", Poster: "mobile accessories.jpg", IsProduct: false},
		{Product_type_id: "cloth", Poster: "cloth.jpg", IsProduct: false},
		{Product_type_id: "mobiles", Poster: "mobiles.jpg", IsProduct: false},
		{Product_type_id: "stationary", Poster: "stationary.jpg", IsProduct: false},
	}
	database.InsertHomeProduct(category)
	fmt.Println("successfully inserted home carts")
}

func insProducts() {
	var products = []shared.Product{
		{Product_type_id: "cosmetics", Pid: "cos-1", Poster: "perfume_1.jpg", Name: "Janan Eau de Parfum", SKU: "JAN-PFM-50ML", Price: 599, Quantity: 10, Brand: "Janan", Category: "Perfume", Color: "Clear", Material: "Glass bottle / liquid", Weight: "50 ml", Size: "50 ml", OriginalPrice: "799", Sale: true, Discount: 25, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-2", Poster: "perfume_2.jpg", Name: "Daisy Eau de Toilette", SKU: "DAI-ET-30ML", Price: 459, Quantity: 10, Brand: "Daisy", Category: "Perfume", Color: "Pale Yellow", Material: "Glass bottle / liquid", Weight: "30 ml", Size: "30 ml", OriginalPrice: "659", Sale: true, Discount: 30, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-3", Poster: "powder_1.jpg", Name: "Pond's Dreamflower Talc", SKU: "PON-TLC-400G", Price: 999, Quantity: 10, Brand: "Pond's", Category: "Talcum Powder", Color: "White", Material: "Plastic bottle / powder", Weight: "400 g", Size: "400 g", OriginalPrice: "1299", Sale: true, Discount: 23, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-4", Poster: "mascara_1.jpg", Name: "Voluminous Waterproof Mascara", SKU: "VOL-MSC-8ML", Price: 250, Quantity: 10, Brand: "Voluminous", Category: "Mascara", Color: "Black", Material: "Plastic tube / cream", Weight: "8 ml", Size: "Standard", OriginalPrice: "350", Sale: true, Discount: 29, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-5", Poster: "lipstick_1.jpg", Name: "Remee Matte Lipstick – Cherry Red", SKU: "REM-LIP-CR01", Price: 260, Quantity: 10, Brand: "Remee", Category: "Lipstick", Color: "Cherry Red", Material: "Plastic case / stick", Weight: "3.5 g", Size: "Standard", OriginalPrice: "349", Sale: true, Discount: 25, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-6", Poster: "foundation_1.jpg", Name: "Lakmé Invisible Finish Foundation (Shade 04)", SKU: "LAK-FND-25ML-04", Price: 299, Quantity: 10, Brand: "Lakmé", Category: "Foundation", Color: "Warm Beige", Material: "Glass bottle / liquid", Weight: "25 ml", Size: "25 ml", OriginalPrice: "399", Sale: true, Discount: 25, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-7", Poster: "facewash_4.jpg", Name: "Pond's Pure Bright Facewash", SKU: "PON-FW-150ML", Price: 599, Quantity: 10, Brand: "Pond's", Category: "Face Wash", Color: "Charcoal Grey", Material: "Plastic tube / gel", Weight: "150 ml", Size: "150 ml", OriginalPrice: "749", Sale: true, Discount: 20, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-8", Poster: "facewash_3.jpg", Name: "Himalaya Neem Face Wash", SKU: "HIM-FW-100ML", Price: 459, Quantity: 10, Brand: "Himalaya", Category: "Face Wash", Color: "Green Gel", Material: "Plastic tube / gel", Weight: "100 ml", Size: "100 ml", OriginalPrice: "575", Sale: true, Discount: 20, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-9", Poster: "facewash_2.jpg", Name: "Carlton Fresh Foam Cleanser", SKU: "CAR-FW-120ML", Price: 999, Quantity: 10, Brand: "Carlton", Category: "Face Wash", Color: "White Foam", Material: "Plastic bottle / foam", Weight: "120 ml", Size: "120 ml", OriginalPrice: "1299", Sale: true, Discount: 23, IsProduct: true},
		{Product_type_id: "cosmetics", Pid: "cos-10", Poster: "facewash_1.jpg", Name: "Beardo Deep Clean Facewash", SKU: "BRD-FW-200ML", Price: 999, Quantity: 10, Brand: "Beardo", Category: "Face Wash", Color: "Transparent Gel", Material: "Plastic tube / gel", Weight: "200 ml", Size: "200 ml", OriginalPrice: "1399", Sale: true, Discount: 29, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-1", Poster: "bracelet_1.jpg", Name: "Royal Charm Bracelet", SKU: "SKU001", Price: 1200, Quantity: 10, Brand: "AuraGold", Category: "Bracelet", Color: "Gold", Material: "Gold", Weight: "10g", Size: "M", OriginalPrice: "1500", Sale: true, Discount: 20, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-2", Poster: "bracelet_2.jpg", Name: "Elegant Drape Bracelet", SKU: "SKU002", Price: 1100, Quantity: 8, Brand: "LuxeBand", Category: "Bracelet", Color: "Gold", Material: "Gold", Weight: "9g", Size: "S", OriginalPrice: "1400", Sale: true, Discount: 21, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-3", Poster: "chain_1.jpg", Name: "Stellar Silver Chain", SKU: "SKU003", Price: 2500, Quantity: 5, Brand: "NovaShine", Category: "Chain", Color: "Silver", Material: "Silver", Weight: "15g", Size: "L", OriginalPrice: "2800", Sale: true, Discount: 10, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-4", Poster: "chain_2.jpg", Name: "Regal Gold Chain", SKU: "SKU004", Price: 2600, Quantity: 7, Brand: "CrownLinks", Category: "Chain", Color: "Gold", Material: "Gold", Weight: "16g", Size: "L", OriginalPrice: "3000", Sale: true, Discount: 13, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-5", Poster: "chain_3.jpg", Name: "Twilight Shine Chain", SKU: "SKU005", Price: 2450, Quantity: 6, Brand: "Ornamo", Category: "Chain", Color: "Gold", Material: "Gold", Weight: "14g", Size: "M", OriginalPrice: "2700", Sale: true, Discount: 9, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-6", Poster: "chain_4.jpg", Name: "Lunar Grace Chain", SKU: "SKU006", Price: 2300, Quantity: 9, Brand: "ZephyrJewels", Category: "Chain", Color: "Silver", Material: "Silver", Weight: "13g", Size: "M", OriginalPrice: "2500", Sale: true, Discount: 8, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-7", Poster: "ring_1.jpg", Name: "Celestial Halo Ring", SKU: "SKU007", Price: 900, Quantity: 12, Brand: "InfinityOrnaments", Category: "Ring", Color: "Gold", Material: "Gold", Weight: "5g", Size: "S", OriginalPrice: "1000", Sale: true, Discount: 10, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-8", Poster: "ring_2.jpg", Name: "Dusk Whisper Ring", SKU: "SKU008", Price: 850, Quantity: 14, Brand: "Lumineux", Category: "Ring", Color: "Silver", Material: "Silver", Weight: "4.5g", Size: "M", OriginalPrice: "950", Sale: true, Discount: 11, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-9", Poster: "ring_3.jpg", Name: "Blush Bloom Ring", SKU: "SKU009", Price: 950, Quantity: 11, Brand: "RoséAllure", Category: "Ring", Color: "Rose Gold", Material: "Gold", Weight: "5.5g", Size: "S", OriginalPrice: "1050", Sale: true, Discount: 9, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-10", Poster: "jumkha_1.jpg", Name: "Golden Twilight Jhumka", SKU: "SKU010", Price: 1800, Quantity: 4, Brand: "Tradiva", Category: "Jhumka", Color: "Gold", Material: "Gold", Weight: "12g", Size: "M", OriginalPrice: "2000", Sale: true, Discount: 10, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-11", Poster: "jumkha_2.jpg", Name: "Silver Dewdrop Jhumka", SKU: "SKU011", Price: 1750, Quantity: 6, Brand: "EthnoGleam", Category: "Jhumka", Color: "Silver", Material: "Silver", Weight: "11g", Size: "M", OriginalPrice: "1900", Sale: true, Discount: 8, IsProduct: true},
		{Product_type_id: "jewels", Pid: "jewl-12", Poster: "jumkha_3.jpg", Name: "Rose Dawn Jhumka", SKU: "SKU012", Price: 1850, Quantity: 5, Brand: "Kritika Jewels", Category: "Jhumka", Color: "Rose Gold", Material: "Gold", Weight: "11.5g", Size: "M", OriginalPrice: "2100", Sale: true, Discount: 12, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-1", Poster: "mobilecase_1.png", Name: "Silicone Back Cover", SKU: "MA-001", Price: 249, Quantity: 75, Brand: "Spigen", Category: "Case", Color: "Black", Material: "Silicone", Weight: "100g", Size: "Medium", OriginalPrice: "399", Sale: true, Discount: 38, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-2", Poster: "mobilecase_2.jpg", Name: "Shockproof Hard Cover", SKU: "MA-002", Price: 299, Quantity: 60, Brand: "Caseology", Category: "Case", Color: "Red", Material: "Polycarbonate", Weight: "120g", Size: "Medium", OriginalPrice: "499", Sale: true, Discount: 40, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-3", Poster: "mobilecase_3.jpg", Name: "Transparent TPU Case", SKU: "MA-003", Price: 199, Quantity: 90, Brand: "Ringke", Category: "Case", Color: "Clear", Material: "TPU", Weight: "80g", Size: "Medium", OriginalPrice: "299", Sale: true, Discount: 33, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-4", Poster: "charger_1.jpg", Name: "18W Fast Charger", SKU: "MA-004", Price: 549, Quantity: 40, Brand: "MI", Category: "Charger", Color: "White", Material: "Plastic", Weight: "150g", Size: "Small", OriginalPrice: "749", Sale: true, Discount: 27, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-5", Poster: "headphone_1.jpg", Name: "Wired Headphones", SKU: "MA-005", Price: 999, Quantity: 30, Brand: "boAt", Category: "Headphones", Color: "Blue", Material: "Plastic", Weight: "250g", Size: "Medium", OriginalPrice: "1399", Sale: true, Discount: 29, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-6", Poster: "headphone_2.jpg", Name: "Wireless On-Ear Headphones", SKU: "MA-006", Price: 1799, Quantity: 20, Brand: "JBL", Category: "Headphones", Color: "Black", Material: "Plastic", Weight: "280g", Size: "Large", OriginalPrice: "2299", Sale: true, Discount: 22, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-7", Poster: "headphone_3.jpg", Name: "Bluetooth Neckband", SKU: "MA-007", Price: 749, Quantity: 35, Brand: "Noise", Category: "Headphones", Color: "Grey", Material: "Plastic", Weight: "200g", Size: "Medium", OriginalPrice: "999", Sale: true, Discount: 25, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-8", Poster: "mobilestand_1.jpg", Name: "Foldable Mobile Stand", SKU: "MA-008", Price: 159, Quantity: 80, Brand: "Amkette", Category: "Stand", Color: "Black", Material: "Metal", Weight: "180g", Size: "Medium", OriginalPrice: "249", Sale: true, Discount: 36, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-9", Poster: "powerbank_1.jpg", Name: "10000mAh Power Bank", SKU: "MA-009", Price: 1299, Quantity: 25, Brand: "Realme", Category: "Power Bank", Color: "White", Material: "Plastic", Weight: "300g", Size: "Medium", OriginalPrice: "1799", Sale: true, Discount: 27, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-10", Poster: "speaker_1.jpg", Name: "Portable Bluetooth Speaker", SKU: "MA-010", Price: 1499, Quantity: 18, Brand: "Zebronics", Category: "Speaker", Color: "Red", Material: "Plastic", Weight: "400g", Size: "Medium", OriginalPrice: "1899", Sale: true, Discount: 21, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-11", Poster: "tws_1.jpg", Name: "True Wireless Earbuds TWS-X1", SKU: "MA-011", Price: 999, Quantity: 45, Brand: "OnePlus", Category: "TWS", Color: "White", Material: "Plastic", Weight: "150g", Size: "Small", OriginalPrice: "1499", Sale: true, Discount: 33, IsProduct: true},
		{Product_type_id: "mobile accessories", Pid: "mob_acc-12", Poster: "tws_2.jpg", Name: "Wireless Earbuds TWS Pro", SKU: "MA-012", Price: 1199, Quantity: 50, Brand: "boAt", Category: "TWS", Color: "Black", Material: "Plastic", Weight: "160g", Size: "Small", OriginalPrice: "1799", Sale: true, Discount: 33, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-1", Poster: "baby_1.jpg", Name: "Baby Romper - Stars", SKU: "CLB-101", Price: 299, Quantity: 50, Brand: "TinyHugs", Category: "baby wear", Color: "blue", Material: "cotton", Weight: "200g", Size: "S", OriginalPrice: "399", Sale: true, Discount: 25, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-2", Poster: "baby_2.jpg", Name: "Infant Onesie - Bunny Print", SKU: "CLB-102", Price: 319, Quantity: 60, Brand: "SoftNest", Category: "baby wear", Color: "white", Material: "organic cotton", Weight: "180g", Size: "S", OriginalPrice: "419", Sale: true, Discount: 23, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-3", Poster: "baby_3.jpg", Name: "Baby Suit - Polka Dots", SKU: "CLB-103", Price: 350, Quantity: 40, Brand: "LittleJoy", Category: "baby wear", Color: "pink", Material: "cotton blend", Weight: "210g", Size: "M", OriginalPrice: "450", Sale: true, Discount: 22, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-4", Poster: "baby_4.jpg", Name: "Newborn Set - Stars", SKU: "CLB-104", Price: 499, Quantity: 30, Brand: "SoftNest", Category: "baby wear", Color: "yellow", Material: "fleece", Weight: "300g", Size: "M", OriginalPrice: "599", Sale: true, Discount: 17, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-5", Poster: "baby_5.jpg", Name: "Toddler Dress - Floral", SKU: "CLB-105", Price: 449, Quantity: 45, Brand: "TinyHugs", Category: "baby wear", Color: "green", Material: "cotton", Weight: "250g", Size: "L", OriginalPrice: "549", Sale: true, Discount: 18, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-6", Poster: "shirt_1.jpg", Name: "Men's Formal Shirt", SKU: "CLM-201", Price: 899, Quantity: 100, Brand: "Eleganz", Category: "shirt", Color: "white", Material: "cotton", Weight: "400g", Size: "L", OriginalPrice: "1099", Sale: true, Discount: 18, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-7", Poster: "shirt_2.jpg", Name: "Men's Casual Shirt", SKU: "CLM-202", Price: 799, Quantity: 80, Brand: "StreetStyle", Category: "shirt", Color: "checked", Material: "cotton blend", Weight: "420g", Size: "M", OriginalPrice: "999", Sale: true, Discount: 20, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-8", Poster: "coat_1.jpg", Name: "Winter Coat - Long", SKU: "CLC-301", Price: 2499, Quantity: 20, Brand: "FrostWear", Category: "coat", Color: "black", Material: "wool", Weight: "1.2kg", Size: "XL", OriginalPrice: "2999", Sale: true, Discount: 17, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-9", Poster: "coat_2.jpg", Name: "Blazer - Slim Fit", SKU: "CLC-302", Price: 2299, Quantity: 25, Brand: "SharpLook", Category: "coat", Color: "navy blue", Material: "polyester", Weight: "1kg", Size: "L", OriginalPrice: "2699", Sale: true, Discount: 15, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-10", Poster: "chudi_1.jpg", Name: "Women's Chudi - Floral", SKU: "CLW-401", Price: 1099, Quantity: 40, Brand: "DesiQueen", Category: "chudi", Color: "maroon", Material: "cotton silk", Weight: "600g", Size: "M", OriginalPrice: "1299", Sale: true, Discount: 15, IsProduct: true},
		{Product_type_id: "cloth", Pid: "cloth-11", Poster: "saree_1.jpg", Name: "Designer Saree - Traditional", SKU: "CLW-402", Price: 1599, Quantity: 35, Brand: "RajTex", Category: "saree", Color: "red", Material: "silk", Weight: "750g", Size: "free", OriginalPrice: "1899", Sale: true, Discount: 16, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-1", Poster: "box_1.jpg", Name: "Geometry Box - Classic", SKU: "STN-101", Price: 120, Quantity: 80, Brand: "Classmate", Category: "geometry box", Color: "blue", Material: "plastic", Weight: "250g", Size: "standard", OriginalPrice: "150", Sale: true, Discount: 20, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-2", Poster: "box_2.jpg", Name: "Maths Box - Premium", SKU: "STN-102", Price: 145, Quantity: 90, Brand: "Doms", Category: "geometry box", Color: "green", Material: "metal", Weight: "300g", Size: "large", OriginalPrice: "180", Sale: true, Discount: 19, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-3", Poster: "box_3.jpg", Name: "Drawing Kit", SKU: "STN-103", Price: 160, Quantity: 70, Brand: "Faber-Castell", Category: "drawing set", Color: "red", Material: "plastic", Weight: "280g", Size: "medium", OriginalPrice: "190", Sale: true, Discount: 16, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-4", Poster: "box_4.jpg", Name: "Compass & Protractor Set", SKU: "STN-104", Price: 95, Quantity: 100, Brand: "Camlin", Category: "geometry tools", Color: "transparent", Material: "plastic", Weight: "150g", Size: "small", OriginalPrice: "125", Sale: true, Discount: 24, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-5", Poster: "pen_1.jpg", Name: "Gel Pen - Blue", SKU: "STN-105", Price: 15, Quantity: 500, Brand: "Reynolds", Category: "pen", Color: "blue", Material: "plastic", Weight: "10g", Size: "regular", OriginalPrice: "20", Sale: true, Discount: 25, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-6", Poster: "pen_2.jpg", Name: "Ball Pen - Black", SKU: "STN-106", Price: 10, Quantity: 600, Brand: "Cello", Category: "pen", Color: "black", Material: "plastic", Weight: "8g", Size: "regular", OriginalPrice: "15", Sale: true, Discount: 33, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-7", Poster: "pen_3.jpg", Name: "Roller Pen - Premium", SKU: "STN-107", Price: 55, Quantity: 150, Brand: "Pilot", Category: "pen", Color: "blue", Material: "metal", Weight: "20g", Size: "compact", OriginalPrice: "70", Sale: true, Discount: 21, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-8", Poster: "pencil_1.jpg", Name: "HB Pencil - 12 Pack", SKU: "STN-108", Price: 60, Quantity: 120, Brand: "Apsara", Category: "pencil", Color: "black", Material: "wood", Weight: "100g", Size: "standard", OriginalPrice: "75", Sale: true, Discount: 20, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-9", Poster: "pencil_2.jpg", Name: "Drawing Pencil Set", SKU: "STN-109", Price: 110, Quantity: 80, Brand: "Faber-Castell", Category: "pencil", Color: "grey", Material: "graphite", Weight: "130g", Size: "standard", OriginalPrice: "130", Sale: true, Discount: 15, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-10", Poster: "pencil_3.jpg", Name: "Charcoal Pencils - 6 Pack", SKU: "STN-110", Price: 180, Quantity: 60, Brand: "Camlin", Category: "pencil", Color: "black", Material: "charcoal", Weight: "110g", Size: "compact", OriginalPrice: "220", Sale: true, Discount: 18, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-11", Poster: "pencil_4.jpg", Name: "Mechanical Pencil", SKU: "STN-111", Price: 75, Quantity: 90, Brand: "Pentel", Category: "pencil", Color: "silver", Material: "plastic/metal", Weight: "30g", Size: "regular", OriginalPrice: "95", Sale: true, Discount: 21, IsProduct: true},
		{Product_type_id: "stationary", Pid: "stationary-12", Poster: "note_1.jpg", Name: "Notebook - A5 Ruled", SKU: "STN-112", Price: 65, Quantity: 200, Brand: "Classmate", Category: "notebook", Color: "green", Material: "paper", Weight: "350g", Size: "A5", OriginalPrice: "80", Sale: true, Discount: 19, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-1", Poster: "watch_1.jpg", Name: "Fire-Boltt Ninja", SKU: "MBL-201", Price: 1999, Quantity: 150, Brand: "Fire-Boltt", Category: "smartwatch", Color: "black", Material: "silicone", Weight: "45g", Size: "1.4 inch", OriginalPrice: "2499", Sale: true, Discount: 20, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-2", Poster: "watch_2.jpg", Name: "boAt Wave Call", SKU: "MBL-202", Price: 1799, Quantity: 120, Brand: "boAt", Category: "smartwatch", Color: "blue", Material: "metal", Weight: "50g", Size: "1.69 inch", OriginalPrice: "2299", Sale: true, Discount: 22, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-3", Poster: "mobile_1.jpg", Name: "iKall Z7", SKU: "MBL-203", Price: 4999, Quantity: 80, Brand: "iKall", Category: "smartphone", Color: "black", Material: "plastic", Weight: "170g", Size: "6.0 inch", OriginalPrice: "5999", Sale: true, Discount: 17, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-4", Poster: "mobile_2.jpg", Name: "Realme 13C", SKU: "MBL-204", Price: 8999, Quantity: 100, Brand: "Realme", Category: "smartphone", Color: "blue", Material: "plastic", Weight: "185g", Size: "6.5 inch", OriginalPrice: "10499", Sale: true, Discount: 14, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-5", Poster: "mobile_3.jpg", Name: "Samsung S23", SKU: "MBL-205", Price: 69999, Quantity: 60, Brand: "Samsung", Category: "smartphone", Color: "green", Material: "glass/metal", Weight: "168g", Size: "6.1 inch", OriginalPrice: "74999", Sale: true, Discount: 7, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-6", Poster: "mobile_4.jpg", Name: "Vivo V4", SKU: "MBL-206", Price: 15999, Quantity: 90, Brand: "Vivo", Category: "smartphone", Color: "purple", Material: "glass", Weight: "180g", Size: "6.4 inch", OriginalPrice: "17999", Sale: true, Discount: 11, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-7", Poster: "mobile_5.jpg", Name: "Galaxy Z Fold3 | Flip 5G", SKU: "MBL-207", Price: 134999, Quantity: 40, Brand: "Samsung", Category: "foldable phone", Color: "phantom black", Material: "glass/aluminum", Weight: "271g", Size: "7.6 inch", OriginalPrice: "149999", Sale: true, Discount: 10, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-8", Poster: "mobile_6.jpg", Name: "Samsung Galaxy Flip", SKU: "MBL-208", Price: 99999, Quantity: 50, Brand: "Samsung", Category: "foldable phone", Color: "lavender", Material: "glass/aluminum", Weight: "183g", Size: "6.7 inch", OriginalPrice: "109999", Sale: true, Discount: 9, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-9", Poster: "mobile_7.jpg", Name: "Redmi 14 5G", SKU: "MBL-209", Price: 11999, Quantity: 110, Brand: "Redmi", Category: "smartphone", Color: "grey", Material: "plastic", Weight: "190g", Size: "6.6 inch", OriginalPrice: "13999", Sale: true, Discount: 14, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-10", Poster: "mobile_8.jpg", Name: "Google Pixel 7a", SKU: "MBL-210", Price: 43999, Quantity: 70, Brand: "Google", Category: "smartphone", Color: "snow", Material: "plastic", Weight: "193g", Size: "6.1 inch", OriginalPrice: "49999", Sale: true, Discount: 12, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-11", Poster: "mobile_9.jpg", Name: "Vivo V20s", SKU: "MBL-211", Price: 20999, Quantity: 85, Brand: "Vivo", Category: "smartphone", Color: "sky blue", Material: "glass", Weight: "180g", Size: "6.44 inch", OriginalPrice: "22999", Sale: true, Discount: 8, IsProduct: true},
		{Product_type_id: "mobiles", Pid: "mobile-12", Poster: "watch_3.jpg", Name: "Noise ColorFit Ultra", SKU: "MBL-212", Price: 2499, Quantity: 140, Brand: "Noise", Category: "smartwatch", Color: "silver", Material: "aluminum", Weight: "48g", Size: "1.75 inch", OriginalPrice: "2999", Sale: true, Discount: 17, IsProduct: true},
	}

	database.InsertProduct(products)
	fmt.Println("inserted all products to database")
}
